# Generated by Django 5.2.4 on 2025-08-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_blog_image_alter_transaction_type_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
